### ISSUE TITLE
Can't upload Arduino 

### ISSUE THREAD

**Issue by RinGal** [96boards/Sensor_Mezzanine_Getting_Started#3]
I'm using Dragonboard 410c and trying to follow the instruction; the program with c++ demo is working fine, but the one with Arduino can't working...It keep displaying can't find Arduino connection...

Is there anything wrong, or the Arduino chip is failure? Any way I can verify?

Thanks.

**Comment by RinGal** [comment]
root@linaro-alip:~/Starter_Kit_for_96Boards/button_led# make upload reset_stty
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [COMPUTED]           ARDMK_DIR = /usr/share/arduino (relative to Common.mk)
- [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 105
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt (from ARDUINO_DIR)
- [DEFAULT]            USER_LIB_PATH = /root/sketchbook/libraries (in user sketchbook)
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [DEFAULT]            BOARD_TAG = uno
- [COMPUTED]           OBJDIR = build-uno (from BOARD_TAG)
- [ASSUMED]            MONITOR_BAUDRATE = 9600
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD = -std=gnu99
- [COMPUTED]           DEVICE_PATH = /dev/tty96B0 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders (from ARDUINO_DIR)
-------------------------
mkdir -p build-uno
make reset
make[1]: Entering directory '/root/Starter_Kit_for_96Boards/button_led'
/usr/bin/ard-reset-arduino  /dev/tty96B0
make[1]: Leaving directory '/root/Starter_Kit_for_96Boards/button_led'
make do_upload
make[1]: Entering directory '/root/Starter_Kit_for_96Boards/button_led'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -D -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -c arduino -b 115200 -P /dev/tty96B0 \
                -U flash:w:build-uno/button_led.hex:i
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00

avrdude done.  Thank you.

/usr/share/arduino/Arduino.mk:1203: recipe for target 'do_upload' failed
make[1]: *** [do_upload] Error 1
make[1]: Leaving directory '/root/Starter_Kit_for_96Boards/button_led'
/usr/share/arduino/Arduino.mk:1195: recipe for target 'upload' failed
make: *** [upload] Error 2
root@linaro-alip:~/Starter_Kit_for_96Boards/button_led#

**Comment by dbharbin** [comment]
Hi RinGal, sorry for the delay in response.  I reproduced your issue and have the most likely solution.  The arduino bootloader on your sensor mezzanine needs re-flashed.  I reprogrammed it using a basic USBtinyISP programmer that you can buy online for ~$10 US and I did it through the Arduino IDE on the DB410c.  
SETUP:  Note that if you use this method, the Sensor Mezzanine is not plugged into the DB410c, but is standalone and connected/powered through the 6-pin cable from the USBtinyISP programmer (Warning: Make sure and get the +5/grd in the right pins, this is not a key connector on the sensor mezzanine, so possible to do this backwards).  The USBtinyISP programmer is connected to the DB410c through a USB port. There are other ways to reflash the bootloader (such as using a repurposed Arduino), but using a USBtinyISP programmer is the easiest.   Let me know if any more questions.
